name: Code Review GPT CI

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  pull-requests: write
  contents: read
  actions: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      GITHUB_SHA: ${{ github.sha }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Build package
        run: bun run build

      - name: Run linting test
        run: bun run lint

      - name: Run unit tests
        run: bun run test

      - name: Run type checking
        run: bun run typecheck

      - name: Run review
        run: bun run start:review --ci=github --model=gpt-4o --debug

      - name: Run prompt tests
        run: bun run dev:test
