name: Release Package
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
        if: ${{ steps.release.outputs.release_created }}
      - run: bun i
        if: ${{ steps.release.outputs.release_created }}
      - run: bun publish:build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }} -f
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -f
